In [1]:
import numpy as np

In [3]:
# Array creation
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
rand = np.random.randint(1, 100, size=(4, 4))

print("1D array: ", arr1d)
print("2D array: ", arr2d)
print("Random 4x4: ", rand)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]
Random 4x4:  [[15 37 55 42]
 [29 36 85  5]
 [53 32 78 72]
 [88 62 75 35]]


In [4]:
# Indexing — get one element
print("First element:", arr1d[0])
print("Row 0, Col 1:", arr2d[0, 1])

First element: 1
Row 0, Col 1: 2


In [7]:
# Slicing — get a range
print("First 3 elements:", arr1d[:3])
print("Last 2 elements:", arr1d[-2:])

First 3 elements: [1 2 3]
Last 2 elements: [4 5]


In [8]:
import numpy as np

In [14]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

In [15]:
# Basic math
print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))
print("Std Dev:", np.std(data))

Sum: 450
Mean: 50.0
Max: 90
Min: 10
Std Dev: 25.81988897471611


In [16]:
# Axis-wise (axis=0 → column-wise, axis=1 → row-wise)
print("Column sums (axis=0):", np.sum(data, axis=0))
print("Row means (axis=1):", np.mean(data, axis=1))

Column sums (axis=0): [120 150 180]
Row means (axis=1): [20. 50. 80.]


In [17]:
# Math operations
arr = np.array([1, 4, 9, 16, 25])
print("Square root:", np.sqrt(arr))
print("Multiply by 2:", arr * 2)
print("Add 10:", arr + 10)

Square root: [1. 2. 3. 4. 5.]
Multiply by 2: [ 2  8 18 32 50]
Add 10: [11 14 19 26 35]


In [19]:
# RESHAPING — change shape without changing data
arr = np.arange(12)  
print("Original: ", arr)

reshaped = arr.reshape(3, 4)   
print("Reshaped to 3x4: ", reshaped)

reshaped2 = arr.reshape(2, 2, 3)  
print("Reshaped to 2x2x3: ", reshaped2)

Original:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3:  [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [21]:
# Flatten back to 1D
flat = reshaped2.flatten()
print("Flattened: ", flat)

Flattened:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
# BROADCASTING — operate on different shaped arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
row_vector = np.array([10, 20, 30])

In [23]:
# NumPy broadcasts row_vector across each row automatically!
result = matrix + row_vector
print("Matrix + row vector: ", result)

Matrix + row vector:  [[11 22 33]
 [14 25 36]]


In [24]:
# Create sample data
sales_data = np.array([[100, 200, 300],
                        [150, 250, 350],
                        [120, 220, 320]])

In [25]:
# Save as .npy (single array)
np.save('sales_data.npy', sales_data)
print("Saved sales_data.npy")

Saved sales_data.npy


In [26]:
# Load it back
loaded = np.load('sales_data.npy')
print("Loaded array: ", loaded)

Loaded array:  [[100 200 300]
 [150 250 350]
 [120 220 320]]


In [27]:
# Save multiple arrays in one .npz file
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.savez('both_arrays.npz', x_data=x, y_data=y)

In [29]:
# Load .npz
data = np.load('both_arrays.npz')
print("x_data:", data['x_data'])
print("y_data:", data['y_data'])

x_data: [1 2 3]
y_data: [4 5 6]


In [30]:
# Save as CSV (human-readable)
np.savetxt('sales.csv', sales_data, delimiter=',', fmt='%d')
loaded_csv = np.loadtxt('sales.csv', delimiter=',')
print("Loaded from CSV: ", loaded_csv)

Loaded from CSV:  [[100. 200. 300.]
 [150. 250. 350.]
 [120. 220. 320.]]


In [31]:
import time

In [32]:
SIZE = 1_000_000  

In [36]:
# Python list approach
py_list = list(range(SIZE))
start = time.time()
result_list = [x * 2 for x in py_list]
list_time = time.time() - start

# NumPy array approach
np_arr = np.arange(SIZE)
start = time.time()
result_numpy = np_arr * 2
numpy_time = time.time() - start

In [37]:
print(f"Python list time : {list_time:.4f} seconds")
print(f"NumPy array time : {numpy_time:.4f} seconds")
print(f"NumPy is {list_time/numpy_time:.1f}x faster!")

Python list time : 0.2285 seconds
NumPy array time : 0.0081 seconds
NumPy is 28.0x faster!


In [38]:
# Memory comparison
import sys
print(f"List memory  : {sys.getsizeof(py_list):,} bytes")
print(f"NumPy memory : {np_arr.nbytes:,} bytes")

List memory  : 8,000,056 bytes
NumPy memory : 8,000,000 bytes
